name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  php:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist
        working-directory: wp-content/plugins/virakcloud-backup
      - name: Lint (PHPCS)
        run: composer lint
        working-directory: wp-content/plugins/virakcloud-backup
      - name: Static Analysis (PHPStan)
        run: composer stan
        working-directory: wp-content/plugins/virakcloud-backup
      - name: Tests (PHPUnit)
        run: composer test
        working-directory: wp-content/plugins/virakcloud-backup
      - name: Build Zip
        run: composer build-zip
        working-directory: wp-content/plugins/virakcloud-backup

